name    'saz-denyhosts'
version '1.1.0'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage denyhosts via Puppet'
project_page 'https://github.com/saz/puppet-denyhosts'
